management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: true

project:
  headPortrait: ?x-oss-process=style/suofang
  requsetTime: 20